// portfolio/src/components/Technologies.vue
<template>
   
   <section class="tecnologias">
        <h2 id="tecno">Tecnologías en las que he trabajado</h2>
        <div class="tech-icons">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-plain.svg" alt="HTML5">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-plain.svg" alt="CSS3">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-plain.svg" alt="Python">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-plain.svg" alt="Java">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-plain.svg" alt="JavaScript">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-plain.svg" alt="Node.js">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-plain.svg" alt="TypeScript">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-plain.svg" alt="MongoDB">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/wordpress/wordpress-plain.svg" alt="WordPress">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg" alt="Express">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg" alt="Sass">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" alt="React">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg" alt="Vue.js">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-plain.svg" alt="Git">
        </div>
    </section>


  </template>

<script>
export default {
  name: "TechnologiesSection"
};
</script>


<style scoped>

.tech-icons img {
    width: 50px;
    margin: 10px;
    transition: transform 0.2s;
}
.tech-icons img:hover {
    transform: scale(1.2);
}

.tecnologias {
  
  
  background-color: #1a1a2e;
  color: #e0e0e0;
  font-family: 'Montserrat', sans-serif;
  border-radius: 9px;
  padding-top: 1px;
  margin-top: 20px;
}

</style>

// apps/client/src/components/Technologies.jsx
import React from 'react';

export default function Technologies() {
  const techRow1 = [
    { name: "Java", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-plain.svg" },
    { name: "Spring Boot", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg" },
    { name: "JavaScript", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-plain.svg" },
    { name: "TypeScript", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-plain.svg" },
    { name: "Node.js", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-plain.svg" },
    { name: "Express", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg" },
    { name: "Python", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-plain.svg" },
    { name: "Git", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-plain.svg" },
    { name: "GitHub", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" },
  ];

  const techRow2 = [
    { name: "HTML5", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-plain.svg" },
    { name: "CSS3", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-plain.svg" },
    { name: "Sass", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg" },
    { name: "React", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
    { name: "Vue.js", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg" },
    { name: "WordPress", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/wordpress/wordpress-plain.svg" },
    { name: "WooCommerce", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/woocommerce/woocommerce-plain.svg" },
    { name: "MySQL", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-plain-wordmark.svg" },
    { name: "PostgreSQL", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-plain-wordmark.svg" },
    { name: "Supabase", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/supabase/supabase-original.svg" },
    { name: "MongoDB", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-plain.svg" },
  ];

  return (
    <section className="technologies-section" id="tecnologías">
      <h2>Mis Herramientas y Tecnologías</h2>

      {/* Row 1: Languages & Backend */}
      <div className="slider-container">
        <div 
          className="slider-track" 
          id="track1"
          style={{ 
            '--item-count': techRow1.length,
            'animationDuration': `${techRow1.length * 2.5}s`
          }}
        >
          {/* Original list */}
          {techRow1.map((tech) => (
            <div className="tech-item" key={tech.name}>
              <img src={tech.logoUrl} alt={tech.name} />
              <p>{tech.name}</p>
            </div>
          ))}
          {/* Cloned list for infinite loop */}
          {techRow1.map((tech) => (
            <div className="tech-item" key={`${tech.name}-clone`} aria-hidden="true">
              <img src={tech.logoUrl} alt={tech.name} />
              <p>{tech.name}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Row 2: Frontend & Databases */}
      <div className="slider-container">
        <div 
          className="slider-track" 
          id="track2"
          style={{ 
            '--item-count': techRow2.length,
            'animationDuration': `${techRow2.length * 2.8}s`
          }}
        >
          {/* Original list */}
          {techRow2.map((tech) => (
            <div className="tech-item" key={tech.name}>
              <img src={tech.logoUrl} alt={tech.name} />
              <p>{tech.name}</p>
            </div>
          ))}
          {/* Cloned list for infinite loop */}
          {techRow2.map((tech) => (
            <div className="tech-item" key={`${tech.name}-clone`} aria-hidden="true">
              <img src={tech.logoUrl} alt={tech.name} />
              <p>{tech.name}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
