// apps/client/src/components/NavBar.jsx
import React, { useState } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import logoUrl from '../assets/logoportfolio.png';

export default function NavBar() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const navigate = useNavigate();
  const location = useLocation();

  const navigation = [
    { id: 1, nombre: 'Experiencia', enlace: '#experiencia' },
    { id: 2, nombre: 'Proyectos', enlace: '#proyectos' },
    { id: 3, nombre: 'Tecnologías', enlace: '#tecnologías' },
    { id: 4, nombre: 'Contacto', enlace: '#contacto' },
  ];

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
    if (!isMenuOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
  };

  const closeMenu = () => {
    setIsMenuOpen(false);
    document.body.style.overflow = '';
  };

  const handleNavClick = (enlace) => {
    closeMenu();
    if (location.pathname !== '/') {
      navigate('/' + enlace);
    } else {
      const element = document.querySelector(enlace);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
      }
    }
  };

  return (
    <nav className="navbar">
      <div className="navbar-brand" onClick={() => navigate('/')} style={{ cursor: 'pointer' }}>
        <img src={logoUrl} alt="Logo" className="navbar-logo" />
      </div>

      <button 
        className={`hamburger ${isMenuOpen ? 'is-active' : ''}`} 
        onClick={toggleMenu}
        aria-label="Abrir menú"
      >
        <span></span>
        <span></span>
        <span></span>
      </button>

      <div className={`navbar-menu ${isMenuOpen ? 'is-open' : ''}`}>
        <ul className="nav-list">
          <li>
            <Link to="/" className="nav-item" onClick={closeMenu}>
              Inicio
            </Link>
          </li>
          {navigation.map((nav) => (
            <li key={nav.id}>
              <a 
                href={nav.enlace}
                className="nav-item" 
                onClick={(e) => {
                  e.preventDefault();
                  handleNavClick(nav.enlace);
                }}
              >
                {nav.nombre}
              </a>
            </li>
          ))}
          <li>
            <Link to="/portfolio-completo" className="nav-item" onClick={closeMenu}>
              Portfolio Completo
            </Link>
          </li>
          <li>
            <Link to="/panel-admin" className="nav-item" onClick={closeMenu}>
              Admin
            </Link>
          </li>
        </ul>
      </div>
    </nav>
  );
}

// src/components/NavBar.vue
<template>
  <nav class="navbar">
    <div class="navbar-brand">
      <!-- Logo -->
      <img src="@/assets/icons/logoportfolio.png" alt="Logo" class="navbar-logo" />
    </div>
    <button class="hamburger" :class="{ 'is-active': isMenuOpen }" @click="toggleMenu">
      <span></span>
      <span></span>
      <span></span>
    </button>
    <div class="navbar-menu" :class="{ 'is-open': isMenuOpen }">
      <ul class="nav-list">
        <li>
          <router-link to="/" class="nav-item" @click="closeMenu">Inicio</router-link>
        </li>
        <li v-for="nav in navegacion" :key="nav.id">
          <router-link :to="{ path: '/', hash: nav.enlace }" class="nav-item" @click="closeMenu">
            {{ nav.nombre }}
          </router-link>
        </li>
        <li>
          <router-link to="/portfolio-completo" class="nav-item" @click="closeMenu">
            Portfolio Completo
          </router-link>
        </li>
      </ul>
    </div>
  </nav>
</template>

<script setup>
import { ref } from 'vue';

const isMenuOpen = ref(false);
const navegacion = ref([
  { id: 1, nombre: 'Experiencia', enlace: '#experiencia' },
  { id: 2, nombre: 'Proyectos', enlace: '#proyect' },
  { id: 3, nombre: 'Contacto', enlace: '#contacto' },
  { id: 4, nombre: 'Tecnologías', enlace: '#tecno' },
]);

const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value;
  document.body.style.overflow = isMenuOpen.value ? 'hidden' : '';
};

const closeMenu = () => {
  isMenuOpen.value = false;
  document.body.style.overflow = '';
};
</script>

<style scoped>
.navbar {
  background: #3209c7;
  color: #fff;
  padding: 0.1rem;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 1000;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.navbar-brand {
  display: flex;
  align-items: center;
}

.navbar-logo {
  height: 65px;
  width: auto;
  margin-left: 1rem; /* Espacio izquierdo en escritorio/tablet */
  margin-right: 0;
  transition: height 0.2s;
}

@media (max-width: 1024px) {
  .navbar {
    padding-right: 1.5rem; /* Agrega espacio al borde derecho */
  }
  .navbar-logo {
    height: 60px;
    margin-left: 1rem;
    margin-right: 0;
  }
}

@media (max-width: 768px) {
   .navbar {
    padding-right: 1.5rem; /* Agrega espacio al borde derecho */
  }
  .navbar-logo {
    height: 60px;
    margin-left: 0;
    margin-right: 1rem; /* Espacio derecho en móvil */
  }
}

@media (max-width: 480px) {
   .navbar {
    padding-right: 1.5rem; /* Agrega espacio al borde derecho */
  }
  .navbar-logo {
    height: 60px;
    margin-left: 0;
    margin-right: 2rem; /* Espacio derecho en móvil */
  }
}

.navbar-menu {
  width: 100%;
  max-width: 1200px;
}

.nav-list {
  list-style: none;
  display: flex;
  justify-content: center;
  gap: 1.5rem;
  margin: 0;
  padding: 0;
}

.nav-item {
  color: #fff;
  text-decoration: none;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  transition: all 0.3s ease;
}

.nav-item:hover {
  background: rgba(255, 255, 255, 0.1);
}

.hamburger {
  display: none;
}

@media (max-width: 768px) {
  .navbar {
    flex-direction: row-reverse;
    justify-content: space-between;
  }
  .navbar-logo {
    margin-right: 0;
    margin-left: 1rem;
  }
  .navbar-brand {
    order: 2;
  }
  .hamburger {
    order: 1;
    display: block;
    background: none;
    border: none;
    padding: 0.5rem;
    cursor: pointer;
    position: absolute;
    left: 1rem;
    top: 50%;
    transform: translateY(-50%);
    z-index: 1001;
  }

  .hamburger span {
    display: block;
    width: 25px;
    height: 3px;
    background: #fff;
    margin: 5px 0;
    transition: all 0.3s ease;
  }

  .hamburger.is-active span:nth-child(1) {
    transform: rotate(45deg) translate(5px, 5px);
  }

  .hamburger.is-active span:nth-child(2) {
    opacity: 0;
  }

  .hamburger.is-active span:nth-child(3) {
    transform: rotate(-45deg) translate(7px, -6px);
  }

  .navbar-menu {
    position: fixed;
    top: 0;
    left: -100%;
    height: 100vh;
    width: 100%;
    background: #3209c7;
    padding-top: 4rem;
    transition: all 0.3s ease;
  }

  .navbar-menu.is-open {
    left: 0;
  }

  .nav-list {
    flex-direction: column;
    align-items: center;
    gap: 2rem;
  }

  .nav-item {
    font-size: 1.2rem;
    width: 100%;
    text-align: center;
    padding: 1rem;
  }
}
</style>
